### ISSUE TITLE
part1

### ISSUE THREAD

**Issue by antonismou** [Asterinos1/neighbour-s-cpu-v2#2]
### I am waiting for part1.

**Comment by Asterinos1** [comment]
coming soon

**Comment by poler2860** [comment]
![504e083b-3c14-42b8-a259-87bab2833139](https://github.com/Asterinos1/neighbour-s-cpu-v2/assets/59158728/b054bb18-24d3-4af0-a914-4eced55a7400)

**Comment by Asterinos1** [comment]
Enough gentlemen
